__
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: castle-image
  labels:
    app: castle-image
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: castle-image
      version: v1
  template:
    metadata:
      labels:
        app: castle-image
        version: v1
    spec:
      containers:
        - name: castle-image
          image: 546703828218.dkr.ecr.ap-northeast-2.amazonaws.com/castle_ecr:1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9000
